Repository vshn/crossplane-service-broker, pull requests merged in 2021-04, with the labels that each got.

#32 Fix binding not found during unbind
  .editorconfig
  pkg/brokerapi/broker.go
  pkg/brokerapi/brokerapi.go
  pkg/brokerapi/brokerapi_test.go
Labels: bug

#33 Implement async bindings
  pkg/brokerapi/broker.go
  pkg/brokerapi/brokerapi.go
  pkg/brokerapi/brokerapi_test.go
  pkg/crossplane/service_mariadb_database.go
  pkg/crossplane/services.go
  pkg/integration/integration.go
Labels: enhancement

#35 Configure Renoate to set labels
  renovate.json
Labels: change

#36 Update brokerapi to v8.0.0
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/brokerapi/broker.go
  pkg/brokerapi/brokerapi.go
  pkg/brokerapi/brokerapi_test.go
  pkg/brokerapi/domain.go
  pkg/crossplane/service_mariadb.go
  pkg/crossplane/service_mariadb_database.go
  pkg/crossplane/service_redis.go
  pkg/reqcontext/reqcontext.go
Labels: dependency

#38 Bearer Token Authentication
  Makefile.vars.mk
  cmd/crossplane-service-broker/main.go
  docs/modules/ROOT/pages/index.adoc
  e2e/Makefile
  e2e/test1.bats
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/auth/basic.go
  pkg/api/auth/bearer_token.go
  pkg/api/auth/middleware.go
  pkg/config/config.go
Labels: enhancement

#42 Methods to easily access Authorization information
  cmd/crossplane-service-broker/main.go
  docs/modules/ROOT/pages/index.adoc
  pkg/api/auth/basic.go
  pkg/api/auth/middleware.go
  pkg/api/auth/principal.go
  pkg/api/auth/principal_test.go
  pkg/brokerapi/brokerapi_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/crossplane/client.go
  pkg/crossplane/metadata.go
  pkg/crossplane/service_mariadb_database.go
  pkg/integration/integration.go
Labels: enhancement
